# Generated by Django 3.0 on 2022-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tipo_habitación', models.CharField(choices=[('1', 'Individual'), ('2', 'Doble'), ('3', 'Triple'), ('4', 'Cuadruples')], max_length=1)),
                ('n_habitacion', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
