# Generated by Django 3.1.1 on 2022-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='id_habitacion',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
