# Generated by Django 3.1.1 on 2022-05-12 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0002_auto_20220510_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='n_habitacion',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
