# Generated by Django 3.1.1 on 2022-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0003_auto_20220512_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='tipo_habitación',
            new_name='tipo_habitacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(default='', upload_to='img/habitaciones/'),
            preserve_default=False,
        ),
    ]
