# Generated by Django 3.1.1 on 2022-05-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0004_auto_20220517_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(upload_to='static/img/habitaciones/'),
        ),
    ]
