# Generated by Django 3.0 on 2022-05-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Habitaciones', '0001_initial'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitación', models.CharField(choices=[('1', 'Individual'), ('2', 'Doble'), ('3', 'Triple'), ('4', 'Cuadruples')], max_length=1)),
                ('cuantia', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Precio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('localizador', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fx_entrada', models.DateField()),
                ('fx_salida', models.DateField()),
                ('cuantia_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente')),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Habitaciones.Habitacion')),
            ],
        ),
    ]
