# Generated by Django 3.1.1 on 2022-05-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0007_auto_20220517_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precio',
            old_name='tipo_habitación',
            new_name='tipo_habitacion',
        ),
    ]
